[package]
name = "ssfp_lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
lazy_static = "1.4.0"
=======
>>>>>>> ed3f166 (cargo inited)
